[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_hello_anchor = "DJ24usMaxgzhmpNdLJHzMCnZ2kayoYv7gBoMGwbHWqK3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/leixinxin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
